### PR TITLE
IDBObjectStore.createIndex should have keyPath with type obj

### PR DESCRIPTION
**Pull request by kentcb**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Looking at [w3c documentation](https://w3c.github.io/IndexedDB/#object-store-interface) it seems like it should be a `string` or `ResizeArray<string>`.

CleanShot 2023-12-15 at 16 56 40@2x

In that case, we could use member overload to cover the API.

If you think `obj` is still the way to go do you have a link to the specification / types that point in that direction ?

**Comment by kentcb** [comment]
I was making it consistent with what's already in use in several places:

- https://github.com/fable-compiler/fable-browser/blob/master/src/IndexedDB/Browser.IndexedDB.fs#L44
- https://github.com/fable-compiler/fable-browser/blob/master/src/IndexedDB/Browser.IndexedDB.fs#L134
- https://github.com/fable-compiler/fable-browser/blob/master/src/IndexedDB/Browser.IndexedDB.fs#L155

**Comment by MangelMaxime** [comment]
Then the problem is that these properties are not typed correctly.

**Comment by MangelMaxime** [comment]
Thank you for the different PRs, I released a new version of the bindings

**Comment by kentcb** [comment]
@MangelMaxime Thanks. Am just trying the latest version now and I find it a tad annoying that `IDBObjectStore.createIndex` has overloads rather than a single method taking `U2<...>`. Would it make more sense to do something like:

```fsharp
type KeyPath = U2<string, ResizeArray<string>>

...

type [<AllowNullLiteral; Global>] IDBObjectStore =
    abstract createIndex: indexName: string * keyPath: KeyPath * ?options: IDBCreateIndexOptions -> IDBRequest
```

At the very least, could there be a `createIndex` overload that takes `U2<...>` rather than me having to map a `U2<...>` onto an appropriate overload (which is my situation)?

**Comment by MangelMaxime** [comment]
In general, overload leads to something closer to standard F#. But I suppose, you have the mapping happening because you get the `keyPath` from one of the properties which returns a `U2`.

I will add another overload `U2<string, ResizeArray<string>>` along side the others overload that I added in the last release. 
This is because in general unwrapping `U2` leads to a closer native F# experience.

Version 2.2.0 has been released with the new overload added to it.

**Pull request merged**
