### PR TITLE
Adding Gamepad

### PR DESCRIPTION
**Pull request by rastreus**
These changes add the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API).

See also the [Using the Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API) documentation for how to use it.

Let me know if this isn't the correct way to contribute this. I wasn't sure how best to organize and contribute everything for this project.

### CODE REVIEW

**Review by alfonsogarciacaro — APPROVED** [review]
Looks good @rastreus, thanks a lot! Only thing is you don't need to update the versions in the .fsproj files. Actually the build script checks when the version in .fsproj is different from RELEASE_NOTES to know the package needs to be published.

Also, we have to add new packages to the `packages` list in build.fsx. But I can do that on my side and push the new releases. BTW, do you want to own or be co-owner of the nuget Fable.Browser.Gamepad?

Thanks again for the contribution!

**Comment by rastreus** [comment]
@alfonsogarciacaro I don't have any experience as a co-owner on nuget, but I am willing to be co-owner if that would be helpful. I just linked my GitHub account to nuget. Let me know if there's anything that I can do to help.

**Comment by alfonsogarciacaro** [comment]
Perfect, I've sent you a request to share ownership of the `Fable.Browser.Gamepad` package 👍 Once you accept it, you only need to follow the instructions to push a new release: https://github.com/fable-compiler/fable-browser#publishing

**Comment by rastreus** [comment]
I accepted the ownership request. Thank you for your help and guidance, Alfonso.

**Pull request merged**
