### PR TITLE
Add PackageLicenseExpression to fsproj.

### PR DESCRIPTION
**Pull request by nojaf**
Tools like https://snyk.io/ would give a warning that the license information is unknown for theses NuGet packages.
To resolve those, I'd like to add [PackageLicenseExpression](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file).

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Because `fable-browser` has the LICENSE file inside the repository I would be in favour of using the existing file.

It can be done quite easily by adding a `Directory.Build.props` at the root of the repository with this content:

```xml
<Project>
	<!-- NuGet Metadata -->
	<PropertyGroup>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="*.fsproj; **\*.fs; **\*.css" PackagePath="fable" />
		<None Include="$(MSBuildThisFileDirectory)\LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)" />
	</ItemGroup>
</Project>
```

That's how I am doing for Fable.Form for example.

Do you know if `https://snyk.io/ ` supports `PackageLicenseFile` ? From what I read on NuGet documentation we can use either `PackageLicenseFile` or `PackageLicenseExpression`.

**Comment by nojaf** [comment]
Hmm, I'm not sure but I would assume Snyk is able to detect both. (if not I'll report that on their end).
I'll create the `Directory.Build.props` file.
How is that picked up by the project files? Do they need a change as well?

**Comment by nojaf** [comment]
@MangelMaxime that doesn't seem to work for me:
image

What am I missing here?

**Comment by MangelMaxime** [comment]
`Directory.Build.props` files is being pickup by `MSBuild` by default.

When executing `MSBuild` will search up for a `Directory.Build.props`. [Documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019)

I am not sure I have 2 hypotheses:
- The `LICENSE` file doesn't have an extension file perhaps MSBuild is not happy?

    I found this [documentation](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-file-without-an-extension). The documentation seems to use the same thing as us however in their linked [example](https://github.com/NuGet/Samples/tree/main/PackageLicenseFileExtensionlessExample) they are using this:

    `<None Include="LICENSE" Pack="true" Visible="false" PackagePath=""/>` note the `Visible` attribute perhaps that's what doing the magic here. 
    
    If it doesn't work, we can just rename the `LICENSE` file to `LICENSE.txt`

- Perhaps, because `global.json` restraint the dotnet core version to 3. On Fable.Form I use .Net 5 to package the projects.

**Comment by nojaf** [comment]
Yep, all good. Let me know if I need to add anything here.

**Comment by alfonsogarciacaro** [comment]
Should we merge this as is or try to conform it with https://github.com/fable-compiler/Fable/pull/2441 so besides licence it also addresses the following?

- Icon
- Symbols
- Tags

**Comment by alfonsogarciacaro** [comment]
Scratch that, I had to push a new version so I merged and made the extra changes myself 😅

**Comment by nojaf** [comment]
Thanks Alfonso!
Would you mind publishing:
```
    nuget Fable.Browser.WebRTC
    nuget Fable.Browser.Navigator
    nuget Fable.Browser.Performance
    nuget Fable.Browser.WebSocket
    nuget Fable.Browser.XMLHttpRequest
```
as well? Those are the packages that were reported by snyk for this repository.

**Comment by alfonsogarciacaro** [comment]
Done!

**Comment by nojaf** [comment]
Thank you!

**Comment by nojaf** [comment]
Hey Alfonso, I can confirm this is working out. Snyk is no longer reporting these issues.
That being said, my list was incomplete I'm afraid.
Could you also publish:
Fable.Browser.Blob
Fable.Browser.Geolocation
Fable.Browser.MediaStream
Fable.Browser.WebStorage
Fable.Browser.Worker

I believe we don't have direct dependencies on these, but they are still reported by Snyk as they are dependencies of other packages.

**Comment by MangelMaxime** [comment]
Hello @alfonsogarciacaro @nojaf 

I re-published all the packages so now they should all have the lincence information in them and depends on packages with licence information in them too.

**Comment by nojaf** [comment]
Thank you Maxime!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @nojaf 

I unlisted the previously released package because they were dependent on FSharp.Core 5.0.0.

I republished new version of package which make the requirement on FSharp.Core down to 4.7.2.

**Pull request merged**
