### PR TITLE
Remove usages of non-existant generic parameters (redone)

### PR DESCRIPTION
**Pull request by jwosty**
New attempt at https://github.com/fable-compiler/fable-browser/pull/79, except replacing ``'Out`` with ``unit`` instead of ``obj`` as per code review.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by jwosty** [comment]
Do you have any way to test this? I have not tested it.

**Comment by MangelMaxime** [comment]
@jwosty The Fable.Browser API doesn't have any tests in it. So for now, we test it manually directly in our own projects directly 🙈 or via Fable REPL to see if its compile and works.

**Comment by alfonsogarciacaro** [comment]
image

**Comment by alfonsogarciacaro** [comment]
I've recently been using Web Test Runner. It makes it really easy to run tests against a headless Chrome and it works with Github Actions too. We could use it to set up some tests but it's a HUGE amount of work to properly test all the bindings, not sure if there are some tests from Typescript that we can try to translate automatically.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I think we can do it small bit by small bit.

Would you be able to set up the Web Test Runner with the Github action?

I am planning to fix https://github.com/fable-compiler/fable-browser/issues/47 since a long time and would need a CI setup for that. If you are happy with Web Test Runner I would be happy to use it instead of Mocha here.

**Pull request merged**
