### PR TITLE
Make CustomEvent Generic

### PR DESCRIPTION
**Pull request by AngelMunoz**
Addresses #65 

**Offtopic**
Also, not related with this PR, can we make the global.json
```jsonc
{
  "sdk": {
    "version": "3.1.300",
    "rollForward": "major" // <- major instead of minor
  }
}
```
so we can build it with .NET5 as well?

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks for the PR @AngelMunoz! I think this is a good change. I was wondering if CustomEvent was used by other packages but it doesn't seem to be the case so hopefully the breaking change doesn't have a big impact. But I'm also thinking we have the possibility to have **both** the untyped `CustomEvent` and generic `CustomEvent<'T>` so there won't be any breaking changes. Or would this be more confusing?

About the global.json, yes, that makes sense. I can make the change :+1:

**Comment by AngelMunoz** [comment]
I think this might be confusing for some people and since I'm the one who wanted to report the change in all of these years it might mean that people don't really use this most likely due react's popularity in the fable ecosystem

I'm neutral  so let me know I can add them as well

**Comment by alfonsogarciacaro** [comment]
Makes sense! Ok, let's use the generic version instead :+1: If someone complains we can still bring back the untyped one 😸

BTW, at the end I've updated global.json to dotnet sdk 5 in line with other Fable repos. Hope that works for you.

**Comment by AngelMunoz** [comment]
regarding the package.json that should work! thanks for the fast response on this!

**Pull request merged**
