### PR TITLE
webrtc bindings

### PR DESCRIPTION
**Pull request by Titaye**
Hello I worked on bindings to WebRTC in the last few days.
It includes dependencies to MediaStreams and ArrayBuffer. 
Are you interested in merging those projet to the global fable-browser repo or do you prefer I manage those projets on my own ?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @Titaye , I think it makes sense to have them in this repo, so everything stays together.

**Comment by alfonsogarciacaro** [comment]
Hi @Titaye, thanks a lot for this! Yes, if these are bindings for a browser native API I also agree it makes sense to put them here. What's your Nuget account? I can publish the packages and make you a collaborator (or vice versa).

**Comment by Titaye** [comment]
Same account as my github accout: titaye
I'll be glad to help to maintain those packages.

**Comment by alfonsogarciacaro** [comment]
That's great to hear @Titaye!

At the end, I've added the Typed Array bindings to Fable.Core to avoid confusion as there was already an `ArrayBuffer` type there (and also because some users were asking to put the Typed Array bindings back into Fable.Core), I hope that's ok with you.

I've published the two other packages and sent you invitations to become owner. I released them as beta for now, but you can just push a stable version if you prefer. I've extended the publishing instructions in the README file, please let me know if you have any other question.

Thanks again!

**Comment by Titaye** [comment]
Thanks, that's perfect.
No question so far.

**Pull request merged**
